global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "url_monitor_api"
    static_configs:
      - targets: ["api:3000"]
  
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]